@{
'ButtonCreate.Name' = 'ButtonCreate'
'ComboBoxDay.Name' = 'ComboBoxDay'
'TextBox1.Name' = 'TextBox1'
'TextBox2.Name' = 'TextBox2'
'ComboBoxMMW.Name' = 'ComboBoxMMW'
'ComboBoxDL.Name' = 'ComboBoxDL'
'Label1.Name' = 'Label1'
'Label2.Name' = 'Label2'
'Label3.Name' = 'Label3'
'Label4.Name' = 'Label4'
'Label5.Name' = 'Label5'
'TextBox3.Name' = 'TextBox3'
'TextBox4.Name' = 'TextBox4'
'Label6.Name' = 'Label6'
'Label7.Name' = 'Label7'
'ComboBoxMSUpdate.Name' = 'ComboBoxMSUpdate'
'Label8.Name' = 'Label8'
'$this.Name' = 'Form1'
'CheckBox1.Name' = 'CheckBox1'
'CheckBox2.Name' = 'CheckBox2'
'ClipCheckBox.Name' = 'ClipCheckBox'
'XMLCheckBox.Name' = 'XMLCheckBox'
'MaskedTextBox1.Name' = 'MaskedTextBox1'
'DateTimePicker1.Name' = 'DateTimePicker1'
'DateTimePickerStart.Name' = 'DateTimePickerStart'
'DateTimePickerEnd.Name' = 'DateTimePickerEnd'
}
